In [15]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df_2009 = pd.read_csv("hads2009RAW.csv")
df_2013 = pd.read_csv("hads2013RAW.csv")

In [9]:
df_2009.head()

,CONTROL,AGE1,ASSISTED,BEDRMS,BUILT,METRO3,NUNITS,OTHERCOST,OWNRENT,PER,...,TOTSAL,TYPE,UTILITY,VACANCY,VALUE,WEIGHT,ZADEQ,ZINC2,ZSMHC,IPOV
0,'100003130103',87,-9,3,2006,'3',1,310.000000,'1',2,...,0,1,229.166667,-6,50000,2772.262855,'1',65250,594,12956
1,'100003130203',70,-9,3,2006,'3',1,222.750000,'1',1,...,0,1,355.416667,-6,238000,2876.223614,'1',35400,684,10292
2,'100006370140',48,-9,4,1985,'5',1,79.166667,'1',4,...,58932,1,199.000000,-6,200000,2706.242657,'1',74932,1549,22159
3,'100006520140',62,-9,3,1985,'5',1,0.000000,'1',2,...,0,1,173.000000,-6,175000,2426.802292,'1',30950,817,14370
4,'100007130148',30,0,2,1980,'1',8,9.000000,'2',2,...,15600,1,113.000000,-6,-6,3089.847859,'1',15600,701,14774

In [13]:
print(df_2009.shape)
df_2009.describe()

(49090, 25)

,AGE1,ASSISTED,BEDRMS,BUILT,NUNITS,OTHERCOST,PER,ROOMS,STRUCTURETYPE,TOTSAL,TYPE,UTILITY,VACANCY,VALUE,WEIGHT,ZINC2,ZSMHC,IPOV
count,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,49090.000000,4.909000e+04,49090.000000,49090.000000,49090.000000,49090.000000
mean,45.975494,-6.237217,2.731330,1966.605663,10.854655,65.146089,1.812508,5.659014,1.820208,45298.951212,1.070931,217.876475,-5.350581,1.580466e+05,2421.073136,60433.449277,1124.424384,14784.868649
std,23.334608,4.203958,1.074593,26.548263,44.166826,131.636006,2.720870,1.840352,1.442531,60711.763762,0.441280,145.428821,2.199443,2.502019e+05,1117.188639,67975.602097,1070.901344,6885.135524
min,-9.000000,-9.000000,0.000000,1919.000000,-7.000000,0.000000,-6.000000,1.000000,-9.000000,-9.000000,1.000000,0.000000,-6.000000,-6.000000e+00,0.000000,-26976.000000,-6.000000,-6.000000
25%,34.000000,-9.000000,2.000000,1950.000000,1.000000,0.000000,1.000000,4.000000,1.000000,0.000000,1.000000,116.500000,-6.000000,-6.000000e+00,1791.244489,17999.000000,451.000000,11165.000000
50%,48.000000,-9.000000,3.000000,1970.000000,1.000000,37.500000,2.000000,6.000000,1.000000,27196.000000,1.000000,200.666667,-6.000000,9.000000e+04,2509.802762,42000.000000,868.000000,14370.000000
75%,61.000000,0.000000,3.000000,1990.000000,2.000000,75.000000,3.000000,7.000000,2.000000,68000.000000,1.000000,292.000000,-6.000000,2.200000e+05,2959.307998,80700.000000,1470.000000,17292.000000
max,93.000000,1.000000,10.000000,2009.000000,981.000000,5297.333333,14.000000,21.000000,6.000000,685928.000000,9.000000,1263.000000,5.000000,2.465647e+06,42391.251192,852840.000000,13803.000000,47759.000000

In [16]:
df_2009.corr()

,AGE1,ASSISTED,BEDRMS,BUILT,NUNITS,OTHERCOST,PER,ROOMS,STRUCTURETYPE,TOTSAL,TYPE,UTILITY,VACANCY,VALUE,WEIGHT,ZINC2,ZSMHC,IPOV
AGE1,1.000000,-0.040759,0.113922,-0.041086,-0.015662,0.112570,0.491999,0.140514,-0.107222,-0.015150,0.007069,0.166712,-0.695649,0.151783,0.017802,0.123502,0.131322,0.261483
ASSISTED,-0.040759,1.000000,-0.428053,-0.095161,0.192787,-0.292295,0.123686,-0.445404,0.337605,-0.155892,-0.009685,-0.363311,-0.194048,-0.415153,-0.021353,-0.212160,-0.138453,0.072524
BEDRMS,0.113922,-0.428053,1.000000,0.119860,-0.279922,0.154554,0.318511,0.863781,-0.458683,0.299408,-0.052389,0.523906,-0.121872,0.399078,0.070322,0.347977,0.349299,0.373088
BUILT,-0.041086,-0.095161,0.119860,1.000000,0.039967,0.121942,0.023240,0.111247,0.108909,0.112526,0.072227,-0.024303,0.008492,0.091338,0.025492,0.119058,0.127203,0.036875
NUNITS,-0.015662,0.192787,-0.279922,0.039967,1.000000,0.036484,-0.119314,-0.257757,0.438815,-0.071021,-0.015894,-0.231874,0.060434,-0.093617,-0.092113,-0.072662,-0.046875,-0.130103
OTHERCOST,0.112570,-0.292295,0.154554,0.121942,0.036484,1.000000,0.054953,0.188080,-0.039087,0.160862,0.011620,0.136421,-0.046929,0.386971,-0.003496,0.230950,0.324626,0.038541
PER,0.491999,0.123686,0.318511,0.023240,-0.119314,0.054953,1.000000,0.292639,-0.185891,0.327854,-0.013270,0.334604,-0.847821,0.142991,0.173704,0.343701,0.394362,0.940896
ROOMS,0.140514,-0.445404,0.863781,0.111247,-0.257757,0.188080,0.292639,1.000000,-0.466342,0.346629,-0.072862,0.552631,-0.126766,0.461956,0.042547,0.417185,0.397496,0.332002
STRUCTURETYPE,-0.107222,0.337605,-0.458683,0.108909,0.438815,-0.039087,-0.185891,-0.466342,1.000000,-0.189817,0.355094,-0.395509,0.102363,-0.275765,0.013224,-0.220412,-0.214629,-0.193832
TOTSAL,-0.015150,-0.155892,0.299408,0.112526,-0.071021,0.160862,0.327854,0.346629,-0.189817,1.000000,-0.059008,0.301551,-0.220355,0.327343,0.039216,0.853176,0.482820,0.355149
TYPE,0.007069,-0.009685,-0.052389,0.072227,-0.015894,0.011620,-0.013270,-0.072862,0.355094,-0.059008,1.000000,-0.054696,0.002219,-0.072516,0.085816,-0.061076,-0.082768,-0.017881
UTILITY,0.166712,-0.363311,0.523906,-0.024303,-0.231874,0.136421,0.334604,0.552631,-0.395509,0.301551,-0.054696,1.000000,-0.206791,0.368005,0.009390,0.362654,0.435211,0.360985
VACANCY,-0.695649,-0.194048,-0.121872,0.008492,0.060434,-0.046929,-0.847821,-0.126766,0.102363,-0.220355,0.002219,-0.206791,1.000000,-0.079972,-0.170504,-0.262536,-0.311683,-0.634311
VALUE,0.151783,-0.415153,0.399078,0.091338,-0.093617,0.386971,0.142991,0.461956,-0.275765,0.327343,-0.072516,0.368005,-0.079972,1.000000,0.000744,0.439054,0.549775,0.142921
WEIGHT,0.017802,-0.021353,0.070322,0.025492,-0.092113,-0.003496,0.173704,0.042547,0.013224,0.039216,0.085816,0.009390,-0.170504,0.000744,1.000000,0.025906,0.003090,0.144760
ZINC2,0.123502,-0.212160,0.347977,0.119058,-0.072662,0.230950,0.343701,0.417185,-0.220412,0.853176,-0.061076,0.362654,-0.262536,0.439054,0.025906,1.000000,0.525760,0.341901
ZSMHC,0.131322,-0.138453,0.349299,0.127203,-0.046875,0.324626,0.394362,0.397496,-0.214629,0.482820,-0.082768,0.435211,-0.311683,0.549775,0.003090,0.525760,1.000000,0.389222
IPOV,0.261483,0.072524,0.373088,0.036875,-0.130103,0.038541,0.940896,0.332002,-0.193832,0.355149,-0.017881,0.360985,-0.634311,0.142921,0.144760,0.341901,0.389222,1.000000